# config context path to "/" by setting an empty string
server:
  contextPath:


# jdbc_config
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048

mybatis:
  mapper-locations: classpath:cn/anniweiya/system/mapper/xml/*Mapper.xml
  typeAliasesPackage: cn.anniweiya.system.entity

logging:
  level:
    root: INFO
#    org:
#      springframework:
#      web: ERROR

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

